/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayAlg */

#ifndef _Included_ArrayAlg
#define _Included_ArrayAlg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayAlg
 * Method:    multiply
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_ArrayAlg_multiply
  (JNIEnv *, jclass, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
